# Generated by Django 3.0 on 2020-03-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_the_dog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='where',
            field=models.CharField(default='unknown', max_length=250, verbose_name='the address the user made the request from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greeting',
            name='who',
            field=models.CharField(default='anonymous', max_length=250, verbose_name='the user who made the request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
