# Generated by Django 3.0 on 2020-03-08 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_the_dog', '0005_auto_20200307_2023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ownership',
        ),
    ]
